#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 /local/module/git/repo/ /results/directory/"
    exit 1
fi

module_name="${1##*/}"

label_flag=
getenforce_out="$(getenforce 2>/dev/null)"
if [ $? -eq 0 -a "$getenforce_out" != "Disabled" ]; then
    label_flag=:z
fi

docker run --cap-add=SYS_ADMIN --rm -it -v "$1:/source/${module_name}${label_flag}" -v "$2:/results${label_flag}" asamalik/build-module /usr/bin/mbs-manager build_module_locally "file:////source/${module_name}?#master"

