#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 /local/module/git/repo/ /results/directory/"
    exit 1
fi

docker run --cap-add=SYS_ADMIN --rm -it -v "$1:/source/$(basename $1)" -v "$2:/results" asamalik/build-module /usr/bin/mbs-manager build_module_locally "file:////source/$(basename $1)?#master"

